version: '3'
services:
  api:
    build:
      context: ./api
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"
  model-serving-node:
    build:
      context: ./model-serving-node
    depends_on:
      - rabbitmq
    scale: 3  # Specify the desired number of worker instances
